# version: '3.7'

# services:
#   app:
#     build:
#       context: ./docker
#       dockerfile: Dockerfile
#     container_name: notifications_app
#     restart: unless-stopped
#     working_dir: /var/www
#     volumes:
#       - ./:/var/www
#     networks:
#       - laravel

#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: notifications_rabbitmq
#     restart: unless-stopped
#     ports:
#       - "5673:5672" 
#       - "15673:15672"
#     networks:
#       - laravel

# networks:
#   laravel:
#     external: true


services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: notifications_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - common_network

  web:
    image: nginx:alpine
    container_name: notifications_web
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /path/to/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - common_network

networks:
  common_network:
    external: true
