services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: users_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - common_network

  web:
    image: nginx:alpine
    container_name: users_web
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /path/to/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - common_network

networks:
  common_network:
    driver: bridge

volumes:
  mysql_data:
